message : Empulse
server:
  port: 9090
  

  
eureka:
   client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/} 



spring:
  datasource:
    url: spring.datasource.url:${cloud.services.ams-ui.connection.jdbcUrl:jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/ad_9da0fcff7b4ce21?useSSL=false&user=b810f49b01ba19&password=b0ba8895}



  data:
    mongodb:
      database: Attendance
      host: localhost
      port: 27017

  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQLDialect
    show-sql: true
    

zuul:
  routes:
    employee.path : /manager
    employee.service_id : managers
    
    getApprovalList.path : /getApprovalList
    getApprovalList.service-id : managers
    
    ams.path : /js/ams1.js
    ams.service-id : managers
    
    getPendingList.path : /getPendingList
    getPendingList.service-id : managers
    
    Approved.path : /Approved
    Approved.service-id : managers
    
    

security:
  oauth2:
    client:
      clientId: 0oab1uvlsil8EVVSP0h7
      clientSecret: j2Bd7-7XUNpqTcHuWAvv1xUB_CR3BGBhA81xKjoj
      accessTokenUri: https://dev-987187.oktapreview.com/oauth2/ausb210yj9JGB58ZG0h7/v1/token
      userAuthorizationUri: https://dev-987187.oktapreview.com/oauth2/ausb210yj9JGB58ZG0h7/v1/authorize
      clientAuthenticationScheme: form
      scope: openid profile email
      
    resource:
      userInfoUri: https://dev-987187.oktapreview.com/oauth2/ausb210yj9JGB58ZG0h7/v1/userinfo
      preferTokenInfo: false
